= Overview

本项目主要内容为企业的微服务应用间通信的架构设计与实现。
主旨为简化微服务应用间通信的代码设计开发。

== 期望遵守的原则或设计思想

* 关注点分离
* 单一职责原则
* DRY
* DDD
* 开箱即用，约定大于配置

== 设计思路

. 基于 Java-Library 构建微服务间的公共通信数据领域模型
. 基于 Spring-boot-starter 技术封装企业微服务应用的 OpenAPI 集



== 微服务带来的挑战

在单体架构下，如果一个领域需要另外一个领域的数据，可通过服务内通信的方式（比如方法调用）。在微服务架构下，一个服务需要另外一个服务的数据，
则需要服务间通信。服务间通信的方式有许多，对于 restful 风格的 Web 应用，一般使用 http 进行远程过程调用。在基于 SpringBoot 技术，我们则可以
选择 Spring 技术栈中的 OpenFeign 组件进行实现。那么就会有一个这样的步骤：

. Service-A 设计并开放出一个 Restful API
. Service-B 需要调用 Service-A 的 开放 API，则需要通过 @FeignClient 注解标记一个 Spring式的 Bean 类。该类定义了 Service-A 的所有开放 API，
当然是按需定义。（大多数情况下不可能需要Service-A的所有API），API的调用方式、请求路径、请求参数、响应，数据格式交换的处理，甚至有可能需要对某个API进行错误或异常处理。

如果 Service-A 需要 Service-B 的某个 OpenAPI，那么 Service-B 同样需要以上的开发步骤。
目前来看，开发体验其实还好，但是随着微服务应用越来越多，业务的复杂性上升，服务间的调用像一张蜘蛛网的时候，可以看到，Service-C 需要 Service-A 的
OpenAPI 时，Service-C 里一定充斥者和 Service-B 相似的代码及结构。那 D、E、F、G 呢。。。。。当 Service-A 的某个 API 进行变更了，废弃了
可想而知，后期开发的维护工作呈数量级的上升。其次，对于稳定的团队，可能维护工作还能接受，当流动性变大，那么这个团队的项目新人友好度便是较低的。
随之带来的就是整体团队的效率下降。

== 解决方案

基于个人的见识和学识，想到的方案就是将其抽取成公共类库，每个服务通过依赖的方式进行获取对应的OpenAPI。这个项目即是演示了如何进行抽取公共类库，包括了
公共类库的项目组织结构设计以及如何使用。

期望的开发步骤

. 在公共类库中定义数据交换模型、定义OpenAPI
. 在调用方应用中，依赖公共类库。具体使用则就跟 Java 的类方法调用一样。
. 在各种服务增加 OpenAPI 时，公共类库在一次迭代中增加，然后更新公共类库版本号。外部应用则升级版本号，即可拿到最新的 OpenAPI 集


主要效果

. 减少了重复定义 FeignClient
. 减少了重复定义各种API的信息：数据交换格式、路径、参数、响应、异常/错误处理等
. 增强了可维护性，可读性。减少了单个微服务的复杂度，代码量


下一阶段：
如何让其他项目通过该项目可以自组织它们特有的通信方式，（遵循DRY原则，我这边定义好了，那么其他项目是不是可以不用再重复设计，而是开箱即用，拿来即用呢）

// 关于企业项目的应用通信的组织方式与实践
// todo 项目名称不应叫 learning-modular，应该叫 learning-application-communication















// todo 统一的请求编码器
// todo 统一的请求解码器
// todo 异常处理及错误码设计
// todo 更改模块名称

// yaml配置设计 spring 的openfeign 可能做了类似设计，可以参考或者结合
//  web.application.{app-name} // web应用
//  web.application.{order}.host //web应用的主机地址
//  web.application.{order}.port //web应用的端口号
//  web.application.{order}.path //web应用的统一前缀


//  web.response.encoder.enabled = true // todo 启用企业特殊的编码器
//  web.response.decoder.enabled = true // todo 启用响应特殊的解码器
//  请求参数和响应的策略：



