spring:
  application:
    name: app-order
application:
  user:
    host: http://localhost
    path: user
logging:
  level:
    root: debug

server:
  port: 8080
  servlet:
    context-path: "/order"
