spring:
  application:
    name: app-user
server:
  port: 80
  servlet:
    context-path: "/user"
application:
  order:
    host: http://localhost
    port: 8080
    path: order
#    web response 的应用
web:
  response:
    enabled: true


